name: dart_web_test
description: Minimal Dart app compiled via vite-plugin-dart.
version: 0.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  web: ^1.1.1
  http: ^1.6.0
  markdown: ^7.2.2
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.0
